### ISSUE TITLE
Using at base64 hex 

### ISSUE THREAD

**Issue by ashraful1980** [glebarez/padre#10]
Sir,
Good day and hope you are doing well.  

I want to learn from your script decode & encode string. Your software is amazing but i don't know applicable command line; please advice how to find password string as bellow base64 hex (two example). Also i have given command in cmd terminal as use to you: padre -u 'https://target.site/profile.php' -cookie 'SESS=$' 'Gw3kg8e3ej4ai9wffn%2Fd0uRqKzyaPfM2UFq%2F8dWmoW4wnyKZhx07Bg==' i have found as attached error massage. Please help me.....
![Error_Massage](https://user-images.githubusercontent.com/52574658/90227872-201b1700-ddca-11ea-9627-b1d31905d70c.jpg)

YmVzdCBhcmFiaWMgc29uZ3MgbG92ZXMgMjAxMyBub25zdG9wINij2YHYttmEINmF2YYg2KfZhNij2LrYp9mG2Yog2KfZhNit2Kgg2KfZhNis2K/ZitivINmD2YTZhdin2Kog2KfZhNi52LHYqNmK : best arabic songs loves 2013 nonstop

YmM6uxE+N9QBWNm6f1LP1vTUaeUqqE9QZoiL3OBenxgx207qLqPhKhc87FWSAAAtujvi : saad1234

note that as above base64 hex found from google...

**Comment by glebarez** [comment]
Hello!

Apparently, Windows terminal doesn't treat the "'" symbol as a quote, so this quote goes right into URL string, which is not parseable.
Try to replace the single quotes with double quotes, or simply omit them at all.

**Comment by ashraful1980** [comment]
Dear Sir,
I have remove the symbol & run the program: padre -u https://target.site/profile.php -cookie SESS=$ Gw3kg8e3ej4ai9wffn%2Fd0uRqKzyaPfM2UFq%2F8dWmoW4wnyKZhx07Bg== 

it is again error massage; as attached. Please help me .....
![Again_Error_Massage](https://user-images.githubusercontent.com/52574658/90261185-7a839a00-de01-11ea-8546-b023579e47d6.jpg)

**Comment by glebarez** [comment]
the https://target.site/profile.php is just an example, and not a really existing site (for now).
