### ISSUE TITLE
Ignore mismatch between certificate name and hostname in the URL

### ISSUE THREAD

**Issue by enricocavalli** [glebarez/padre#13]
Is it possibile to add maybe a copule of options to relax x509 certificate checks in requests? 

- ignore errors about unknown CA (or self signed certificates)
- ignore certificate name vs URL hostname mismatch?

Both check can be bypassed for instance using burp proxy and trusting burp CA at "system level", but it could be useful to fire padre without proxies in between.

Thanks a lot !

**Comment by glebarez** [comment]
Fixed in [Release 2.0.4](https://github.com/glebarez/padre/releases/tag/v2.0.4)
Thank you for reporting
