### ISSUE TITLE
Add in project travis-ci.org

### ISSUE THREAD

**Issue by mirecl** [glebarez/padre#8]
Hi, man!!!
Your project is amazing. Just not enough travis-ci.
I hope you change your mind and add it!

**Comment by glebarez** [comment]
Hey there, great idea.
I've added automated Build workflow to automatically test the build on all major OS'es (Linux, Windows, MacOS).
I also posted some automated badges using great shields.io.
Check out here:
See https://github.com/glebarez/padre/pull/11
